#!/usr/bin/env node
// Explicit, offline import of the reviewed canonical guides. Never run at build time.
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { posix } from 'node:path';

const [checkout, revision, ...extra] = process.argv.slice(2);
if (!checkout || !/^[0-9a-f]{40}$/.test(revision ?? '') || extra.length) {
  console.error('Usage: npm run sync:v2-docs -- /path/to/trusted-checkout FULL_COMMIT_SHA');
  process.exit(1);
}

const guides = ['getting-started', 'working-with-your-agent', 'verification',
  'usage-reporting', 'packaging', 'host-support'];
const routes = new Map(guides.map((name) => [`docs/${name}.md`, `/docs/v2/${name}/`]));
const sourceBase = `https://github.com/shakacode/agent-workflows-v2/blob/${revision}/`;
const destination = new URL('../src/pages/docs/v2/', import.meta.url);

function rewriteLink(href) {
  if (/^(?:[a-z][a-z0-9+.-]*:|\/|#)/i.test(href)) return href;
  const [, file, suffix] = href.match(/^([^?#]*)(.*)$/);
  if (!file) return href;
  const sourcePath = posix.normalize(posix.join('docs', file));
  return `${routes.get(sourcePath) ?? `${sourceBase}${sourcePath}`}${suffix}`;
}

// These guides use inline Markdown links. Leave fenced examples and inline code
// untouched; only link destinations change, including their query/fragment suffixes.
function rewriteLinks(markdown) {
  let fence;
  return markdown.split('\n').map((line) => {
    const marker = line.match(/^\s{0,3}(`{3,}|~{3,})/);
    if (marker) {
      if (!fence) fence = marker[1];
      else if (marker[1][0] === fence[0] && marker[1].length >= fence.length) fence = undefined;
      return line;
    }
    if (fence) return line;
    return line.split(/(`+[^`]*`+)/g).map((part, index) => index % 2 ? part
      : part.replace(/(\]\()([^\s)]+)(\))/g, (_, open, href, close) => `${open}${rewriteLink(href)}${close}`))
      .join('');
  }).join('\n');
}

// Read and prepare the whole allowlist before writing any generated page.
const pages = guides.map((name) => {
  const sourcePath = `docs/${name}.md`;
  const markdown = execFileSync('git', ['-C', checkout, 'show', `${revision}:${sourcePath}`], { encoding: 'utf8' });
  const heading = markdown.match(/^# (.+)\r?\n\r?\n/);
  if (!heading) throw new Error(`${sourcePath}: expected a leading Markdown title`);
  const body = markdown.slice(heading[0].length);
  const description = body.split(/\r?\n\r?\n/)[0].replace(/\r?\n/g, ' ');
  return [name, `---
layout: ../../../layouts/Doc.astro
title: ${JSON.stringify(heading[1])}
eyebrow: V2 · Work-in-progress pilot
description: ${JSON.stringify(description)}
---

<!-- Generated by scripts/sync-v2-docs.mjs. Edit the canonical source, then refresh. -->

[V2 pilot overview](/docs/v2/)

${rewriteLinks(body)}
<details>
<summary>About this guide</summary>

Maintained in the V2 repository. This page uses [source revision ${revision.slice(0, 7)}](${sourceBase}${sourcePath}).

</details>
`];
});

mkdirSync(destination, { recursive: true });
for (const [name, markdown] of pages) {
  writeFileSync(new URL(`${name}.md`, destination), markdown);
}
console.log(`sync-v2-docs: imported ${pages.length} guides at ${revision}`);
